// --- Gêneros ---
MERGE (drama:Genre {type: "Drama"})
MERGE (sciFi:Genre {type: "Sci-Fi"})
MERGE (action:Genre {type: "Action"})
MERGE (comedy:Genre {type: "Comedy"})

// --- Filmes e Séries ---
MERGE (titanic:Movie {title: "Titanic"})
MERGE (inception:Movie {title: "Inception"})
MERGE (matrix:Movie {title: "The Matrix"})
MERGE (darkKnight:Movie {title: "The Dark Knight"})
MERGE (the100:Series {title: "The 100"})
MERGE (strangerThings:Series {title: "Stranger Things"})
MERGE (friends:Series {title: "Friends"})
MERGE (forrestGump:Movie {title: "Forrest Gump"})
MERGE (laLaLand:Movie {title: "La La Land"})
MERGE (godfather:Movie {title: "The Godfather"})

// --- Relacionamentos de gêneros ---
MERGE (titanic)-[:IN_GENRE]->(drama)
MERGE (inception)-[:IN_GENRE]->(sciFi)
MERGE (matrix)-[:IN_GENRE]->(action)
MERGE (darkKnight)-[:IN_GENRE]->(action)
MERGE (the100)-[:IN_GENRE]->(sciFi)
MERGE (strangerThings)-[:IN_GENRE]->(sciFi)
MERGE (friends)-[:IN_GENRE]->(comedy)
MERGE (forrestGump)-[:IN_GENRE]->(drama)
MERGE (laLaLand)-[:IN_GENRE]->(drama)
MERGE (godfather)-[:IN_GENRE]->(drama)

// --- Usuários ---
MERGE (alice:Viewer {name: "Alice"})
MERGE (bob:Viewer {name: "Bob"})
MERGE (carla:Viewer {name: "Carla"})
MERGE (diego:Viewer {name: "Diego"})
MERGE (emily:Viewer {name: "Emily"})
MERGE (fabio:Viewer {name: "Fábio"})
MERGE (gina:Viewer {name: "Gina"})
MERGE (hugo:Viewer {name: "Hugo"})

// --- Avaliações e conteúdos assistidos ---
MERGE (alice)-[:WATCHED {rating: 5}]->(titanic)
MERGE (alice)-[:WATCHED {rating: 4}]->(the100)
MERGE (bob)-[:WATCHED {rating: 4}]->(matrix)
MERGE (bob)-[:WATCHED {rating: 5}]->(strangerThings)
MERGE (carla)-[:WATCHED {rating: 5}]->(darkKnight)
MERGE (carla)-[:WATCHED {rating: 3}]->(friends)
MERGE (diego)-[:WATCHED {rating: 5}]->(forrestGump)
MERGE (diego)-[:WATCHED {rating: 4}]->(laLaLand)
MERGE (emily)-[:WATCHED {rating: 4}]->(the100)
MERGE (emily)-[:WATCHED {rating: 5}]->(strangerThings)
MERGE (fabio)-[:WATCHED {rating: 3}]->(matrix)
MERGE (fabio)-[:WATCHED {rating: 4}]->(darkKnight)
MERGE (gina)-[:WATCHED {rating: 5}]->(friends)
MERGE (gina)-[:WATCHED {rating: 4}]->(laLaLand)
MERGE (hugo)-[:WATCHED {rating: 5}]->(godfather)
MERGE (hugo)-[:WATCHED {rating: 4}]->(titanic)

// --- Atores e Diretores ---
MERGE (leo:Actor {name: "Leonardo DiCaprio"})-[:ACTED_IN]->(titanic)
MERGE (kate:Actor {name: "Kate Winslet"})-[:ACTED_IN]->(titanic)
MERGE (leoNolan:Director {name: "Christopher Nolan"})-[:DIRECTED]->(inception)
MERGE (keanu:Actor {name: "Keanu Reeves"})-[:ACTED_IN]->(matrix)
MERGE (chris:Director {name: "Christopher Nolan"})-[:DIRECTED]->(darkKnight)
MERGE (matt:Actor {name: "Matthew Perry"})-[:ACTED_IN]->(friends)
MERGE (millie:Actor {name: "Millie Bobby Brown"})-[:ACTED_IN]->(strangerThings)
